{{- if .Values.global.database.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: pg-postgresql
type: Opaque
data:
  postgres-password: {{ .Values.global.database.password | b64enc }}
{{- end }}
