// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/mmcdole/gofeed"
	"readflow.ai/goserver/db/adb"
	db2 "readflow.ai/goserver/db/rdb"
	"readflow.ai/goserver/graph"
	"readflow.ai/goserver/service"
)

// Injectors from wire.go:

func InitializeResolver(adb *db.PrismaClient, rdb *db2.PrismaClient) (*graph.Resolver, error) {
	parser := newFeedParser()
	feedService := service.NewFeedService(rdb, parser)
	resolver := graph.NewResolver(adb, rdb, feedService)
	return resolver, nil
}

// wire.go:

func newFeedParser() *gofeed.Parser {
	return gofeed.NewParser()
}
